/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import java.awt.HeadlessException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.print.attribute.Size2DSyntax.MM;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jorgeantoniogarciagomez
 */
public class Concurso extends javax.swing.JInternalFrame {
    
    Conexion mConexion = new Conexion();
    DatosConcurso mDatosConcurso = new DatosConcurso();
    public int idConcurso = 0, HoraLimite = 0, MinutoLimite = 0, Dia = 0, Mes = 0, Año = 0, ContadorColumna = 1, ContadorColumna2 = 1, ContadorColumna3 = 1, ContadorColumna4 = 1, IDconcurso;
    public String Descripcion;
    int Seleccion = 0, Seleccion2 = 0, idViejo = 0, HorasViejas = 0, MinViejos = 0;
    int ID = 0, ID2 = 0;
    //DatosConcurso mDatosConcurso;
    DefaultTableModel Tabla = new DefaultTableModel();
    DefaultTableModel Tabla2 = new DefaultTableModel();
    DefaultTableModel Tabla3 = new DefaultTableModel();
    DefaultTableModel Tabla4 = new DefaultTableModel();
    
    DateFormat df = DateFormat.getDateInstance();

    /**
     * Creates new form Concurso
     */
    public Concurso() {
        initComponents();
        ConsultaTabla();
        ConsultaTabla2();
        ConsultaTabla3();
        consultaCon();
        LBL_Mensajero1.setText("");
        LBL_Mensajero2.setText("");
        LBL_Mensajero3.setText("");
        LBL_Mensajero4.setText("");
        TXTnombreBaja.setEditable(false);
        LBLidCambios.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BTNalta = new javax.swing.JButton();
        CBhora = new javax.swing.JComboBox<>();
        CBminutos = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TXTdescripcion = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        TBLaltaConcursos = new javax.swing.JTable();
        LBL_Mensajero2 = new javax.swing.JLabel();
        DCfechaAlta = new com.toedter.calendar.JDateChooser();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        BTNborrar = new javax.swing.JButton();
        LBL_Mensajero1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBLConcursos = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        TXTnombreBaja = new javax.swing.JTextField();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        TXTnombreCambios = new javax.swing.JTextField();
        BTNmodificar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TBLcambios = new javax.swing.JTable();
        LBL_Mensajero3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        CBhorasCambios = new javax.swing.JComboBox<>();
        CBminCambios = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        LBLidCambios = new javax.swing.JLabel();
        DCfechaCambios = new com.toedter.calendar.JDateChooser();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        TXTnombreConsulta = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        TBLconsulta = new javax.swing.JTable();
        LBL_Mensajero4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBorder(null);

        jLabel2.setText("Fecha:");

        jLabel3.setText("Descripción:");

        jLabel4.setText("Tiempo límite:");

        BTNalta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/16 (User add).jpg"))); // NOI18N
        BTNalta.setText("Dar de alta");
        BTNalta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNaltaActionPerformed(evt);
            }
        });

        CBhora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));

        CBminutos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        jLabel8.setText("Horas");

        jLabel9.setText("Minutos");

        TBLaltaConcursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TBLaltaConcursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBLaltaConcursosMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(TBLaltaConcursos);

        LBL_Mensajero2.setText("- ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBhora, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(CBminutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LBL_Mensajero2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(223, 223, 223)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(BTNalta))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel9))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(106, 106, 106)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TXTdescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                                .addComponent(DCfechaAlta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(DCfechaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(TXTdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CBminutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CBhora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNalta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBL_Mensajero2)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Alta", jPanel1);

        jPanel3.setMaximumSize(new java.awt.Dimension(3276, 32767));
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 580));

        BTNborrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/16 (Delete).jpg"))); // NOI18N
        BTNborrar.setText("Borrar");
        BTNborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNborrarActionPerformed(evt);
            }
        });

        TBLConcursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBLConcursosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBLConcursos);

        jLabel6.setText("Nombre del concurso:");

        TXTnombreBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTnombreBajaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNborrar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBL_Mensajero1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(TXTnombreBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 1, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TXTnombreBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(BTNborrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LBL_Mensajero1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(300, 300, 300))
        );

        jTabbedPane2.addTab("Dar de baja un concurso.", jPanel3);

        jTabbedPane1.addTab("Baja", jTabbedPane2);

        jLabel13.setText("Descripcion:");

        BTNmodificar.setText("Modificar");
        BTNmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNmodificarActionPerformed(evt);
            }
        });

        TBLcambios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TBLcambios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBLcambiosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TBLcambios);

        LBL_Mensajero3.setText("jLabel15");

        jLabel15.setText("Fecha:");

        jLabel16.setText("Tiempo Limite:");

        CBhorasCambios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));

        CBminCambios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        jLabel17.setText("Horas");

        jLabel18.setText("Minutos");

        LBLidCambios.setText("ID");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(LBL_Mensajero3, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addGap(18, 18, 18)
                                    .addComponent(CBhorasCambios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(jLabel18))
                                        .addComponent(CBminCambios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel15))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TXTnombreCambios, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                                        .addComponent(DCfechaCambios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTNmodificar)
                            .addComponent(LBLidCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(DCfechaCambios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(TXTnombreCambios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(CBhorasCambios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBminCambios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBLidCambios))
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNmodificar)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LBL_Mensajero3)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Modificar un concurso", jPanel4);

        jTabbedPane1.addTab("Cambios", jTabbedPane3);

        jLabel14.setText("Nombre del concurso:");

        TXTnombreConsulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXTnombreConsultaKeyReleased(evt);
            }
        });

        jScrollPane3.setViewportView(TBLconsulta);

        LBL_Mensajero4.setText("jLabel15");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(TXTnombreConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 31, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LBL_Mensajero4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(TXTnombreConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LBL_Mensajero4)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Consultar Concursos", jPanel5);

        jTabbedPane1.addTab("Consulta", jTabbedPane4);

        jPanel2.setBackground(new java.awt.Color(71, 120, 197));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("X");
        jLabel5.setToolTipText("Presione para salir");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jLabel5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel5KeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("APARTADO CONCURSOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(110, 110, 110)
                .addComponent(jLabel5)
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5KeyPressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged

    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed

    }//GEN-LAST:event_jPanel2MousePressed
    public void ConsultaTabla() {
        Tabla = (DefaultTableModel) TBLaltaConcursos.getModel();
        int a = Tabla.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            Tabla.removeRow(Tabla.getRowCount() - 1);
        }
        
        if (mConexion.conectar()) {
            ArrayList mArrayListaConcursos = new ArrayList();
            mArrayListaConcursos = mConexion.ConsultarConcursos();
            
            String[] Datos = null;
            if (mArrayListaConcursos != null) {
                if (ContadorColumna == 1) {
                    Tabla.addColumn("ID");
                    Tabla.addColumn("Descripción");
                    Tabla.addColumn("Fecha");
                    Tabla.addColumn("Tiempo_Límite");
                    ContadorColumna = 2;
                }
                
                for (int i = 0; i < mArrayListaConcursos.size(); i++) {
                    mDatosConcurso = (DatosConcurso) mArrayListaConcursos.get(i);
                    Datos = new String[4];
                    Datos[0] = "" + mDatosConcurso.getIdConcurso();
                    Datos[1] = mDatosConcurso.getDescripcion();
                    Datos[2] = mDatosConcurso.getFecha();
                    Datos[3] = "" + mDatosConcurso.getTiempo();
                    Tabla.addRow(Datos);
                }
                
            } else {
                LBL_Mensajero2.setText("No hay concursos");
            }
            this.TBLaltaConcursos = new javax.swing.JTable();
            this.TBLaltaConcursos.setModel(Tabla);
            this.TBLaltaConcursos.getColumnModel().getColumn(0).setPreferredWidth(50);
            this.TBLaltaConcursos.getColumnModel().getColumn(1).setPreferredWidth(50);
            this.TBLaltaConcursos.getColumnModel().getColumn(2).setPreferredWidth(100);
            this.TBLaltaConcursos.getColumnModel().getColumn(3).setPreferredWidth(100);
            if (this.TBLaltaConcursos.getRowCount() > 0) {
                this.TBLaltaConcursos.setRowSelectionInterval(0, 0);
            }
        } else {
            LBL_Mensajero2.setText("Error al consultar los equipos");
        }
        mConexion.desconectar();
    }

    private void BTNaltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNaltaActionPerformed
        // TODO add your handling code here:
        try {
            //if (TXTdescripcion.getText() != null) { 

            Date d1 = DCfechaAlta.getDate();
            int HoraLim = Integer.parseInt(CBhora.getSelectedItem().toString());
            int MinLim = Integer.parseInt(CBminutos.getSelectedItem().toString());
            String Tiempo1 = HoraLim + ":" + MinLim + ":00";
            
            mDatosConcurso.setDescripcion(this.TXTdescripcion.getText());
            mDatosConcurso.setTiempo(Tiempo1);
            
            String texto = TXTdescripcion.getText();
            texto = texto.replaceAll(" ", "");
            if ((texto.length() == 0) || (texto.length() >= 150) || ((CBhora.getSelectedItem() == "00") && (CBminutos.getSelectedItem() == "00")) || (d1 == null)) {
                LBL_Mensajero2.setText("Debe ingresar todos los datos correctamente");
            } else {
                String Fecha1 = "";
                Fecha1 = new SimpleDateFormat("yyyy-MM-dd").format(DCfechaAlta.getDate());
                mDatosConcurso.setFecha(Fecha1);
                if (mConexion.conectar()) {
                    String NombreEq = mConexion.ConsultaNomConcursos(TXTdescripcion.getText());
                    if (!NombreEq.equals(texto)) {
                        if (mConexion.AltaConcurso(mDatosConcurso)) {
                            LBL_Mensajero2.setText("El concurso fue guardado con éxito");
                            TXTdescripcion.setText("");
                            CBhora.setSelectedIndex(0);
                            CBminutos.setSelectedIndex(0);
                        } else {
                            LBL_Mensajero2.setText("Error al guardar el concurso");
                        }
                    } else {
                        LBL_Mensajero2.setText("Ya existe un concurso con ese nombre");
                    }
                    mConexion.desconectar();
                    ConsultaTabla();
                    ConsultaTabla2();
                    ConsultaTabla3();
                    consultaCon();
                }
            }
            DCfechaAlta.setCalendar(null);
        } catch (HeadlessException | NumberFormatException e) {
            LBL_Mensajero2.setText("POR FAVOR, LLENE BIEN LOS DATOS");
        }
    }//GEN-LAST:event_BTNaltaActionPerformed
    public void ConsultaTabla2() {
        Tabla2 = (DefaultTableModel) TBLConcursos.getModel();
        int a = Tabla2.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            Tabla2.removeRow(Tabla2.getRowCount() - 1);
        }
        
        if (mConexion.conectar()) {
            ArrayList mArrayListConcursos = new ArrayList();
            mArrayListConcursos = mConexion.ConsultarConcursos();
            
            String[] Datos = null;
            if (mArrayListConcursos != null) {
                if (ContadorColumna2 == 1) {
                    Tabla2.addColumn("ID");
                    Tabla2.addColumn("Descripción");
                    Tabla2.addColumn("Fecha");
                    Tabla2.addColumn("Tiempo_Límite");
                    ContadorColumna2 = 2;
                }
                
                for (int i = 0; i < mArrayListConcursos.size(); i++) {
                    mDatosConcurso = (DatosConcurso) mArrayListConcursos.get(i);
                    Datos = new String[4];
                    Datos[0] = "" + mDatosConcurso.getIdConcurso();
                    Datos[1] = mDatosConcurso.getDescripcion();
                    Datos[2] = mDatosConcurso.getFecha();
                    Datos[3] = "" + mDatosConcurso.getTiempo();
                    Tabla2.addRow(Datos);
                }
                
            } else {
                LBL_Mensajero2.setText("No hay concursos");
            }
            this.TBLConcursos = new javax.swing.JTable();
            this.TBLConcursos.setModel(Tabla2);
            this.TBLConcursos.getColumnModel().getColumn(0).setPreferredWidth(50);
            this.TBLConcursos.getColumnModel().getColumn(1).setPreferredWidth(50);
            this.TBLConcursos.getColumnModel().getColumn(2).setPreferredWidth(100);
            this.TBLConcursos.getColumnModel().getColumn(3).setPreferredWidth(100);
            if (this.TBLConcursos.getRowCount() > 0) {
                this.TBLConcursos.setRowSelectionInterval(0, 0);
            }
        } else {
            LBL_Mensajero2.setText("Error al consultar los equipos");
        }
        mConexion.desconectar();
    }

    private void BTNborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNborrarActionPerformed
        // TODO add your handling code here:
        try {
            if (mConexion.conectar()) {
                mDatosConcurso = new DatosConcurso();
                mDatosConcurso.setIdConcurso(ID);
                if (mConexion.EliminarConcurso(mDatosConcurso)) {
                    if (ID != 0) {
                        LBL_Mensajero1.setText("Concurso eliminado con éxito");
                    } else {
                        LBL_Mensajero1.setText("Seleccione un concurso");
                    }
                } else {
                    LBL_Mensajero1.setText("Este concurso no se puede eliminar,tiene relacion con otros registros");
                }
                mConexion.desconectar();
                ConsultaTabla();
                ConsultaTabla2();
                ConsultaTabla3();
                consultaCon();
            }
            TXTnombreBaja.setText("");
        } catch (Exception e) {
            LBL_Mensajero1.setText("ERROR, Seleccione un concurso");
        }
    }//GEN-LAST:event_BTNborrarActionPerformed
    
    public void ConsultaTabla3() {
        Tabla3 = (DefaultTableModel) TBLcambios.getModel();
        int a = Tabla3.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            Tabla3.removeRow(Tabla3.getRowCount() - 1);
        }
        
        if (mConexion.conectar()) {
            ArrayList mArrayListConcursos = new ArrayList();
            mArrayListConcursos = mConexion.ConsultarConcursos();
            
            String[] Datos = null;
            if (mArrayListConcursos != null) {
                if (ContadorColumna3 == 1) {
                    Tabla3.addColumn("ID");
                    Tabla3.addColumn("Descripción");
                    Tabla3.addColumn("Fecha");
                    Tabla3.addColumn("Tiempo_Límite");
                    ContadorColumna3 = 2;
                }
                
                for (int i = 0; i < mArrayListConcursos.size(); i++) {
                    mDatosConcurso = (DatosConcurso) mArrayListConcursos.get(i);
                    Datos = new String[4];
                    Datos[0] = "" + mDatosConcurso.getIdConcurso();
                    Datos[1] = mDatosConcurso.getDescripcion();
                    Datos[2] = mDatosConcurso.getFecha();
                    Datos[3] = "" + mDatosConcurso.getTiempo();
                    Tabla3.addRow(Datos);
                }
                
            } else {
                LBL_Mensajero3.setText("No hay concursos");
            }
            this.TBLcambios = new javax.swing.JTable();
            this.TBLcambios.setModel(Tabla3);
            this.TBLcambios.getColumnModel().getColumn(0).setPreferredWidth(50);
            this.TBLcambios.getColumnModel().getColumn(1).setPreferredWidth(50);
            this.TBLcambios.getColumnModel().getColumn(2).setPreferredWidth(100);
            this.TBLcambios.getColumnModel().getColumn(3).setPreferredWidth(100);
            if (this.TBLcambios.getRowCount() > 0) {
                this.TBLcambios.setRowSelectionInterval(0, 0);
            }
        } else {
            LBL_Mensajero3.setText("Error al consultar los equipos");
        }
        mConexion.desconectar();
    }

    private void TBLaltaConcursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBLaltaConcursosMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_TBLaltaConcursosMouseClicked

    private void TBLConcursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBLConcursosMouseClicked
        // TODO add your handling code here:
        Seleccion = TBLConcursos.rowAtPoint(evt.getPoint());
        String TempC = String.valueOf(TBLConcursos.getValueAt(Seleccion, 0));
        TXTnombreBaja.setText(TBLConcursos.getModel().getValueAt(Seleccion, 1).toString());
        ID = Integer.parseInt(TempC);

    }//GEN-LAST:event_TBLConcursosMouseClicked

    private void TXTnombreBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTnombreBajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTnombreBajaActionPerformed

    private void TBLcambiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBLcambiosMouseClicked
        // TODO add your handling code here:
        TXTnombreCambios.setText("");
        Seleccion2 = TBLcambios.rowAtPoint(evt.getPoint());
        LBLidCambios.setText(TBLcambios.getModel().getValueAt(Seleccion2, 0).toString());
        TXTnombreCambios.setText(TBLcambios.getModel().getValueAt(Seleccion2, 1).toString());
        String FechaT = String.valueOf(TBLcambios.getValueAt(Seleccion2, 2)).toString();
        String TemporalHoras = String.valueOf(TBLcambios.getValueAt(Seleccion2, 3)).substring(0, 2);
        String TemporalMinutos = String.valueOf(TBLcambios.getValueAt(Seleccion2, 3)).substring(3, 5);
        
        HorasViejas = Integer.parseInt(TemporalHoras);
        MinViejos = Integer.parseInt(TemporalMinutos);
        
        for (int i = 0; i < CBhorasCambios.getItemCount(); i++) {
            if (HorasViejas == Integer.parseInt(CBhorasCambios.getItemAt(i))) {
                CBhorasCambios.setSelectedIndex(i); //LLENAMOS HORAS
            }
        }
        for (int i = 0; i < CBminCambios.getItemCount(); i++) {
            if (MinViejos == Integer.parseInt(CBminCambios.getItemAt(i))) {
                CBminCambios.setSelectedIndex(i); //LLENAMOS MINUTOS
            }
        }
        SimpleDateFormat formatoDelTexto = new SimpleDateFormat("yy-MM-dd");
        Date fecha = null;
        try {
            fecha = formatoDelTexto.parse(FechaT);
            DCfechaCambios.setDate(fecha);
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_TBLcambiosMouseClicked

    private void BTNmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNmodificarActionPerformed
        // TODO add your handling code here:
        DatosConcurso mDatosConcurso = new DatosConcurso();
        DatosConcurso nDatosConcurso = new DatosConcurso();
        int HoraLim = Integer.parseInt(CBhorasCambios.getSelectedItem().toString());
        int MinLim = Integer.parseInt(CBminCambios.getSelectedItem().toString());
        String Tiempo1 = HoraLim + ":" + MinLim + ":00";
        Date d = DCfechaCambios.getDate();
        
        String texto = TXTnombreCambios.getText();
        texto = texto.replaceAll(" ", "");
        if ((texto.length() == 0) || (texto.length() >= 150) || ((CBhorasCambios.getSelectedItem() == "00") && (CBminCambios.getSelectedItem() == "00")) || (d == null)) {
            LBL_Mensajero3.setText("Debe ingresar todos los datos correctamente");
            LBLidCambios.setText("0");
        } else {
            String fecha = "";
            fecha = new SimpleDateFormat("yyyy-MM-dd").format(DCfechaCambios.getDate());
            if (mConexion.conectar()) {
                if (!"ID".equals(LBLidCambios.getText())) {
                    String NombreEq = mConexion.ConsultaNomConcursos(TXTnombreCambios.getText());
                    if (!LBLidCambios.getText().equals("0")) {
                        if (!NombreEq.equals(texto)) {
                            ID2 = Integer.parseInt(LBLidCambios.getText());
                            mDatosConcurso.setIdConcurso(ID2);
                            nDatosConcurso.setDescripcion(TXTnombreCambios.getText());
                            nDatosConcurso.setFecha(fecha);
                            nDatosConcurso.setTiempo(Tiempo1);
                            if (mConexion.ModificarConcurso(mDatosConcurso, nDatosConcurso) && !LBLidCambios.getText().equals("0")) {
                                LBL_Mensajero3.setText("Concurso modificado exitosamente");
                                LBLidCambios.setText("0");
                            } else {
                                LBL_Mensajero3.setText("Error al modificar");
                                LBLidCambios.setText("0");
                            }
                        } else {
                            LBL_Mensajero3.setText("Ya existe un concurso con ese nombre");
                        }
                    } else {
                        LBL_Mensajero3.setText("Selecciona un concurso de la tabla");
                    }
                } else {
                    LBL_Mensajero3.setText("Selecciona un concurso de la tabla");
                }
            } else {
                LBL_Mensajero3.setText("Error al conectar con la Base de Datos");
            }
            mConexion.desconectar();
            ConsultaTabla();
            ConsultaTabla2();
            ConsultaTabla3();
            consultaCon();
        }
        
        TXTnombreCambios.setText("");
        CBhorasCambios.setSelectedIndex(0);
        CBminCambios.setSelectedIndex(0);
        DCfechaCambios.setCalendar(null);
        LBLidCambios.setText("0");
    }//GEN-LAST:event_BTNmodificarActionPerformed
    
    private void consultaCon() {
        Tabla4 = (DefaultTableModel) TBLconsulta.getModel();
        int a = Tabla4.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            Tabla4.removeRow(Tabla4.getRowCount() - 1);
        }
        
        if (mConexion.conectar()) {
            ArrayList mArrayListaConcursos = new ArrayList();
            mArrayListaConcursos = mConexion.ConsultarConcursos();
            
            String[] Datos = null;
            if (mArrayListaConcursos != null) {
                if (ContadorColumna4 == 1) {
                    Tabla4.addColumn("ID");
                    Tabla4.addColumn("Descripción");
                    Tabla4.addColumn("Fecha");
                    Tabla4.addColumn("Tiempo_Límite");
                    ContadorColumna4 = 2;
                }
                
                for (int i = 0; i < mArrayListaConcursos.size(); i++) {
                    mDatosConcurso = (DatosConcurso) mArrayListaConcursos.get(i);
                    Datos = new String[4];
                    Datos[0] = "" + mDatosConcurso.getIdConcurso();
                    Datos[1] = mDatosConcurso.getDescripcion();
                    Datos[2] = mDatosConcurso.getFecha();
                    Datos[3] = "" + mDatosConcurso.getTiempo();
                    Tabla4.addRow(Datos);
                }
                
            } else {
                LBL_Mensajero4.setText("No hay concursos");
            }
            this.TBLconsulta = new javax.swing.JTable();
            this.TBLconsulta.setModel(Tabla4);
            this.TBLconsulta.getColumnModel().getColumn(0).setPreferredWidth(50);
            this.TBLconsulta.getColumnModel().getColumn(1).setPreferredWidth(50);
            this.TBLconsulta.getColumnModel().getColumn(2).setPreferredWidth(100);
            this.TBLconsulta.getColumnModel().getColumn(3).setPreferredWidth(100);
            if (this.TBLconsulta.getRowCount() > 0) {
                this.TBLconsulta.setRowSelectionInterval(0, 0);
            }
        } else {
            LBL_Mensajero4.setText("Error al consultar los equipos");
        }
        mConexion.desconectar();
    }
    private void TXTnombreConsultaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTnombreConsultaKeyReleased
        // TODO add your handling code here:
        Tabla4 = (DefaultTableModel) TBLconsulta.getModel();
        int a = Tabla4.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            Tabla4.removeRow(Tabla4.getRowCount() - 1);
        }
        
        if (mConexion.conectar()) {
            ArrayList mArrayListaConcursos = new ArrayList();
            mArrayListaConcursos = mConexion.consultarConcursoFiltro(TXTnombreConsulta.getText());
            
            String[] Datos = null;
            if (mArrayListaConcursos != null) {
                if (ContadorColumna4 == 1) {
                    Tabla4.addColumn("ID");
                    Tabla4.addColumn("Descripción");
                    Tabla4.addColumn("Fecha");
                    Tabla4.addColumn("Tiempo_Límite");
                    ContadorColumna4 = 2;
                }
                
                for (int i = 0; i < mArrayListaConcursos.size(); i++) {
                    mDatosConcurso = (DatosConcurso) mArrayListaConcursos.get(i);
                    Datos = new String[4];
                    Datos[0] = "" + mDatosConcurso.getIdConcurso();
                    Datos[1] = mDatosConcurso.getDescripcion();
                    Datos[2] = mDatosConcurso.getFecha();
                    Datos[3] = "" + mDatosConcurso.getTiempo();
                    Tabla4.addRow(Datos);
                }
                
            } else {
                LBL_Mensajero4.setText("No hay concursos");
            }
            this.TBLconsulta = new javax.swing.JTable();
            this.TBLconsulta.setModel(Tabla4);
            this.TBLconsulta.getColumnModel().getColumn(0).setPreferredWidth(50);
            this.TBLconsulta.getColumnModel().getColumn(1).setPreferredWidth(50);
            this.TBLconsulta.getColumnModel().getColumn(2).setPreferredWidth(100);
            this.TBLconsulta.getColumnModel().getColumn(3).setPreferredWidth(100);
            if (this.TBLconsulta.getRowCount() > 0) {
                this.TBLconsulta.setRowSelectionInterval(0, 0);
            }
        } else {
            LBL_Mensajero4.setText("Error al consultar los equipos");
        }
        mConexion.desconectar();
    }//GEN-LAST:event_TXTnombreConsultaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNalta;
    private javax.swing.JButton BTNborrar;
    private javax.swing.JButton BTNmodificar;
    private javax.swing.JComboBox<String> CBhora;
    private javax.swing.JComboBox<String> CBhorasCambios;
    private javax.swing.JComboBox<String> CBminCambios;
    private javax.swing.JComboBox<String> CBminutos;
    private com.toedter.calendar.JDateChooser DCfechaAlta;
    private com.toedter.calendar.JDateChooser DCfechaCambios;
    private javax.swing.JLabel LBL_Mensajero1;
    private javax.swing.JLabel LBL_Mensajero2;
    private javax.swing.JLabel LBL_Mensajero3;
    private javax.swing.JLabel LBL_Mensajero4;
    private javax.swing.JLabel LBLidCambios;
    private javax.swing.JTable TBLConcursos;
    private javax.swing.JTable TBLaltaConcursos;
    private javax.swing.JTable TBLcambios;
    private javax.swing.JTable TBLconsulta;
    private javax.swing.JTextField TXTdescripcion;
    private javax.swing.JTextField TXTnombreBaja;
    private javax.swing.JTextField TXTnombreCambios;
    private javax.swing.JTextField TXTnombreConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    // End of variables declaration//GEN-END:variables
}
