/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jorgeantoniogarciagomez
 */
public class Concurso extends javax.swing.JInternalFrame {
    
    Conexion mConexion = new Conexion();
    DatosConcurso mDatosConcurso = new DatosConcurso();
    public int idConcurso = 0, HoraLimite = 0, MinutoLimite = 0,Dia=0,Mes=0, Año = 0, ContadorColumna = 1, IDconcurso;
    public String Descripcion;
    int Seleccion = 0;
    int ID = 0;
    //DatosConcurso mDatosConcurso;
    DefaultTableModel Tabla = new DefaultTableModel();

    /**
     * Creates new form Concurso
     */
    public Concurso() {
        initComponents();
        ConsultaTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BTNalta = new javax.swing.JButton();
        CBhora = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        CBminutos = new javax.swing.JComboBox<>();
        CBdia = new javax.swing.JComboBox<>();
        CBmes = new javax.swing.JComboBox<>();
        CBaño = new javax.swing.JComboBox<>();
        LBL_Mensajero1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TXTdescripcion = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        TBLaltaConcursos = new javax.swing.JTable();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        BTNbuscar = new javax.swing.JButton();
        BTNborrar = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        TBLConcursos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBorder(null);

        jLabel2.setText("Fecha:");

        jLabel3.setText("Descripción:");

        jLabel4.setText("Tiempo límite:");

        BTNalta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/16 (User add).jpg"))); // NOI18N
        BTNalta.setText("Dar de alta");
        BTNalta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNaltaActionPerformed(evt);
            }
        });

        CBhora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));

        jLabel7.setText(":");

        CBminutos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        CBdia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        CBmes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        CBaño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));

        jLabel8.setText("Horas");

        jLabel9.setText("Minutos");

        jLabel10.setText("Día");

        jLabel11.setText("Mes");

        jLabel12.setText("Año");

        TBLaltaConcursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TBLaltaConcursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBLaltaConcursosMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(TBLaltaConcursos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBhora, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBminutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jLabel11)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(CBdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CBmes, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel12))
                    .addComponent(CBaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(BTNalta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(LBL_Mensajero1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CBmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(TXTdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CBminutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CBhora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel7)))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNalta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBL_Mensajero1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Alta", jPanel1);

        jPanel3.setMaximumSize(new java.awt.Dimension(3276, 32767));
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 580));

        BTNbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/16 (Search).jpg"))); // NOI18N
        BTNbuscar.setText("Buscar");
        BTNbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNbuscarActionPerformed(evt);
            }
        });

        BTNborrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/16 (Delete).jpg"))); // NOI18N
        BTNborrar.setText("Borrar");
        BTNborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNborrarActionPerformed(evt);
            }
        });

        TBLConcursos.setModel(Tabla);
        TBLConcursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBLConcursosMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(TBLConcursos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(BTNbuscar)
                        .addGap(302, 302, 302)
                        .addComponent(BTNborrar))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNborrar)
                    .addComponent(BTNbuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(238, 238, 238))
        );

        jTabbedPane2.addTab("Dar de baja un concurso.", jPanel3);

        jTabbedPane1.addTab("Baja", jTabbedPane2);

        jPanel2.setBackground(new java.awt.Color(71, 120, 197));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("X");
        jLabel5.setToolTipText("Presione para salir");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jLabel5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel5KeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("APARTADO CONCURSOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(110, 110, 110)
                .addComponent(jLabel5)
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5KeyPressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged

    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed

    }//GEN-LAST:event_jPanel2MousePressed
    public void ConsultaTabla() {
        Tabla = (DefaultTableModel) TBLaltaConcursos.getModel();
        int a = Tabla.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            Tabla.removeRow(Tabla.getRowCount() - 1);
        }

        if (mConexion.conectar()) {
            ArrayList mArrayListaConcursos = new ArrayList();
            mArrayListaConcursos = mConexion.ConsultarConcursos();

            String[] Datos = null;
            if (mArrayListaConcursos != null) {
                if (ContadorColumna == 1) {
                    Tabla.addColumn("id");
                    Tabla.addColumn("Descripcion");
                    Tabla.addColumn("Fecha");
                    Tabla.addColumn("Tiempo_Limite");
                    ContadorColumna = 2;
                }

                for (int i = 0; i < mArrayListaConcursos.size(); i++) {
                    mDatosConcurso = (DatosConcurso) mArrayListaConcursos.get(i);
                    Datos = new String[4];
                    Datos[0] = "" + mDatosConcurso.getIdConcurso();
                    Datos[1] = mDatosConcurso.getDescripcion(); 
                    Datos[2] = mDatosConcurso.getFecha(); 
                    Datos[3] = "" + mDatosConcurso.getTiempo();
                    Tabla.addRow(Datos);
                }

            } else {
                LBL_Mensajero1.setText("No hay concursos");
            }
            this.TBLaltaConcursos = new javax.swing.JTable();
            this.TBLaltaConcursos.setModel(Tabla);
            this.TBLaltaConcursos.getColumnModel().getColumn(0).setPreferredWidth(50);
            this.TBLaltaConcursos.getColumnModel().getColumn(1).setPreferredWidth(50);
            this.TBLaltaConcursos.getColumnModel().getColumn(2).setPreferredWidth(100);
            this.TBLaltaConcursos.getColumnModel().getColumn(2).setPreferredWidth(100);
            if (this.TBLaltaConcursos.getRowCount() > 0) {
                this.TBLaltaConcursos.setRowSelectionInterval(0, 0);
            }
        } else {
            LBL_Mensajero1.setText("Error al consultar los equipos");
        }
        mConexion.desconectar();
    }
    
    private void BTNaltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNaltaActionPerformed
        // TODO add your handling code here:
        try {
            //if (TXTdescripcion.getText() != null) { 
            String Anyo = (String) CBaño.getSelectedItem();
            String Mes = (String) CBmes.getSelectedItem();
            String Dia = (String) CBdia.getSelectedItem();
            String Fecha1 = Anyo + "-" + Mes + "-" + Dia;
            int HoraLim = Integer.parseInt(CBhora.getSelectedItem().toString());
            int MinLim = Integer.parseInt(CBminutos.getSelectedItem().toString());
            String Tiempo1 = HoraLim + ":" + MinLim + ":00";
            mDatosConcurso.setFecha(Fecha1);
            mDatosConcurso.setDescripcion(this.TXTdescripcion.getText());
            mDatosConcurso.setTiempo(Tiempo1);
            
            String texto = TXTdescripcion.getText();
            texto = texto.replaceAll(" ", "");
            if (texto.length() == 0) {
                LBL_Mensajero1.setText("Debe ingresar todos los datos correctamente");
            } else {
                if (mConexion.conectar()) {
                    if (mConexion.AltaConcurso(mDatosConcurso)) {
                        LBL_Mensajero1.setText("El concurso fue guardado con éxito");
                        CBdia.setSelectedIndex(0);
                        CBmes.setSelectedIndex(0);
                        CBaño.setSelectedIndex(0);
                        TXTdescripcion.setText("");
                        CBhora.setSelectedIndex(0);
                        CBminutos.setSelectedIndex(0);
                    } else {
                        LBL_Mensajero1.setText("Error al guardar el concurso");
                    }
                    mConexion.desconectar();
                    ConsultaTabla();
                }
            }
        } catch (HeadlessException | NumberFormatException e) {
            LBL_Mensajero1.setText("POR FAVOR, LLENE BIEN LOS DATOS");
        }
    }//GEN-LAST:event_BTNaltaActionPerformed

    private void BTNbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNbuscarActionPerformed
        // TODO add your handling code here:
        //LimpiarTabla();
        DefaultTableModel TablaLimpiar = (DefaultTableModel) TBLConcursos.getModel();
        int a = TBLConcursos.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            TablaLimpiar.removeRow(TablaLimpiar.getRowCount() - 1);
        }
        
        if (mConexion.conectar()) {
            ArrayList mArrayListFechasConcursos = new ArrayList();
            mArrayListFechasConcursos = mConexion.ConsultarConcursos();

            String[] Datos = null;
            if (mArrayListFechasConcursos != null) {
                if (ContadorColumna == 1) {
                    Tabla.addColumn("id");
                    Tabla.addColumn("Descripcion");
                    Tabla.addColumn("Fecha");
                    Tabla.addColumn("Tiempo_Limite");
                    ContadorColumna = 2;
                }

                for (int i = 0; i < mArrayListFechasConcursos.size(); i++) {
                    mDatosConcurso = (DatosConcurso) mArrayListFechasConcursos.get(i);
                    Datos = new String[4];
                    Datos[0] = "" + mDatosConcurso.getIdConcurso();
                    Datos[1] = mDatosConcurso.getDescripcion(); 
                    Datos[2] = mDatosConcurso.getFecha(); 
                    Datos[3] = "" + mDatosConcurso.getTiempo();
                    Tabla.addRow(Datos);
                }

            } else {
                LBL_Mensajero1.setText("No hay concursos");
            }
            this.TBLConcursos = new javax.swing.JTable();
            this.TBLConcursos.setModel(Tabla);
            this.TBLConcursos.getColumnModel().getColumn(0).setPreferredWidth(50);
            this.TBLConcursos.getColumnModel().getColumn(1).setPreferredWidth(50);
            this.TBLConcursos.getColumnModel().getColumn(2).setPreferredWidth(100);
            this.TBLConcursos.getColumnModel().getColumn(2).setPreferredWidth(100);
            if (this.TBLConcursos.getRowCount() > 0) {
                this.TBLConcursos.setRowSelectionInterval(0, 0);
            }

        } else {
            LBL_Mensajero1.setText("Error al consultar");
        }

        mConexion.desconectar();
    }//GEN-LAST:event_BTNbuscarActionPerformed

    private void TBLConcursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBLConcursosMouseClicked
        // TODO add your handling code here:
        Seleccion = TBLConcursos.rowAtPoint(evt.getPoint());
        ID = Integer.parseInt(TBLConcursos.getModel().getValueAt(Seleccion, 0).toString());
    }//GEN-LAST:event_TBLConcursosMouseClicked

    private void BTNborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNborrarActionPerformed
        // TODO add your handling code here:
        if (Seleccion > 0) {
            try {
                if (mConexion.conectar()) {
                    mDatosConcurso = new DatosConcurso();
                    mDatosConcurso.setIdConcurso(ID);
                    if (mConexion.EliminarConcurso(mDatosConcurso)) {
                        LBL_Mensajero1.setText("Concurso eliminado con éxito");
                    } else {
                        LBL_Mensajero1.setText("Este concurso no se puede eliminar,tiene relacion con otros registros");
                    }
                    mConexion.desconectar();
                }

            } catch (Exception e) {
                LBL_Mensajero1.setText("ERROR, Seleccione un concurso");
            }
        } else {
            LBL_Mensajero1.setText("PORFAVOR seleccione un concurso");
        }
        
    }//GEN-LAST:event_BTNborrarActionPerformed

    private void TBLaltaConcursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBLaltaConcursosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TBLaltaConcursosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNalta;
    private javax.swing.JButton BTNborrar;
    private javax.swing.JButton BTNbuscar;
    private javax.swing.JComboBox<String> CBaño;
    private javax.swing.JComboBox<String> CBdia;
    private javax.swing.JComboBox<String> CBhora;
    private javax.swing.JComboBox<String> CBmes;
    private javax.swing.JComboBox<String> CBminutos;
    private javax.swing.JLabel LBL_Mensajero1;
    private javax.swing.JTable TBLConcursos;
    private javax.swing.JTable TBLaltaConcursos;
    private javax.swing.JTextField TXTdescripcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
