/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jorgeantoniogarciagomez
 */
public class Equipos extends javax.swing.JInternalFrame {

    Conexion mConexion = new Conexion();
    DefaultTableModel Tabla = new DefaultTableModel();
    private int Selec = 0;
    DatosEquipo mDatosEquipo;
    private int ID = 0;

    /**
     * Creates new form Equipos
     */
    public Equipos() {
        initComponents();
        mDatosEquipo = new DatosEquipo();
        LBL_Men.setText("");
        LBLmen.setText("");
        LBLmen1.setText("");
        LBLMen.setText("");
        LBLid.setVisible(false);
        LBLid1.setVisible(false);
        Tabla.addColumn("ID");
        Tabla.addColumn("Nombre");
        ConsultaTabla();
        ConsultaTablaAl();
        //TXT_Nom.setEditable(false);
        TXTnom.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TXT_Nom = new javax.swing.JTextField();
        BTN_alta = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblAl = new javax.swing.JTable();
        LBL_Men = new javax.swing.JLabel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        TXTnom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEQ = new javax.swing.JTable();
        BTNelim = new javax.swing.JButton();
        LBLmen = new javax.swing.JLabel();
        LBLid = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        TXTnom1 = new javax.swing.JTextField();
        BTNmod = new javax.swing.JButton();
        LBLid1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_Mod = new javax.swing.JTable();
        LBLmen1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbl_Con = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        TXTcon = new javax.swing.JTextField();
        LBLMen = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setBorder(null);
        setClosable(true);
        setTitle("Equipos");

        jLabel2.setText("Nombre:");

        BTN_alta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/16 (User add).jpg"))); // NOI18N
        BTN_alta.setText("Dar de alta");
        BTN_alta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_altaActionPerformed(evt);
            }
        });

        tblAl.setModel(Tabla);
        jScrollPane4.setViewportView(tblAl);

        LBL_Men.setText("-  ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TXT_Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(BTN_alta))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(LBL_Men, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TXT_Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_alta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBL_Men)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Alta", jPanel4);

        TXTnom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTnomKeyTyped(evt);
            }
        });

        jLabel3.setText("Nombre:");

        tblEQ.setModel(Tabla);
        tblEQ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEQMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEQ);

        BTNelim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/16 (User delete).jpg"))); // NOI18N
        BTNelim.setText("Eliminar");
        BTNelim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNelimActionPerformed(evt);
            }
        });

        LBLmen.setText("* ");

        LBLid.setText(" ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBLmen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LBLid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TXTnom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BTNelim)))
                        .addGap(0, 16, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(LBLid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(BTNelim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBLmen, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Dar de baja un equipo", jPanel5);

        jTabbedPane4.addTab("Baja", jTabbedPane5);

        BTNmod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/16 (User edit).jpg"))); // NOI18N
        BTNmod.setText("Modificar");
        BTNmod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNmodActionPerformed(evt);
            }
        });

        LBLid1.setText("ID");

        tbl_Mod.setModel(Tabla);
        tbl_Mod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ModMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbl_Mod);

        LBLmen1.setText("*");

        jLabel4.setText("Nombre: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXTnom1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTNmod)
                .addGap(39, 39, 39))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBLid1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(104, 104, 104)
                    .addComponent(LBLmen1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBLid1)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNmod)
                    .addComponent(TXTnom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(336, 336, 336)
                    .addComponent(LBLmen1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Modificar un Equipo", jPanel1);

        jTabbedPane4.addTab("Cambios", jTabbedPane1);

        tbl_Con.setModel(Tabla);
        jScrollPane6.setViewportView(tbl_Con);

        jLabel6.setText("Nombre del Equipo: ");

        TXTcon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXTconKeyReleased(evt);
            }
        });

        LBLMen.setText("*");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXTcon, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(LBLMen, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TXTcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBLMen)
                .addGap(12, 12, 12))
        );

        jTabbedPane2.addTab("Consulta de Equipos", jPanel3);

        jTabbedPane4.addTab("Consultas", jTabbedPane2);

        jPanel2.setBackground(new java.awt.Color(71, 120, 197));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("X");
        jLabel5.setToolTipText("Presione para salir");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jLabel5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel5KeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("APARTADO EQUIPOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel5KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel5KeyPressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged

    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed

    }//GEN-LAST:event_jPanel2MousePressed

    public boolean ValidarCajasNom() {
        return !TXT_Nom.getText().equals("");
    }

    public boolean ValidarCajasnom() {
        return !TXTnom.getText().equals("");
    }

    public void ConsultaTabla() {
        Tabla = (DefaultTableModel) tblEQ.getModel();
        int a = Tabla.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            Tabla.removeRow(Tabla.getRowCount() - 1);
        }

        if (mConexion.conectar()) {
            ArrayList mListaEquipos = mConexion.consultaEquipos();
            String[] datos;

            for (Object mListaEquipo : mListaEquipos) {
                datos = new String[2];
                mDatosEquipo = (DatosEquipo) mListaEquipo;
                datos[0] = "" + mDatosEquipo.getId();
                datos[1] = mDatosEquipo.getNombre();
                Tabla.addRow(datos);
            }
            this.tblEQ = new javax.swing.JTable();
            this.tblEQ.setModel(Tabla);
            this.tblEQ.getColumnModel().getColumn(0).setPreferredWidth(50);
            this.tblEQ.getColumnModel().getColumn(1).setPreferredWidth(250);
            if (this.tblEQ.getRowCount() > 0) {
                this.tblEQ.setRowSelectionInterval(0, 0);
            }
        } else {
            LBLmen.setText("Error al consultar los equipos");
        }
        mConexion.desconectar();
    }

    public void consultaTablaMod() {
        Tabla = (DefaultTableModel) tbl_Mod.getModel();
        int a = Tabla.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            Tabla.removeRow(Tabla.getRowCount() - 1);
        }

        if (mConexion.conectar()) {
            ArrayList mListaEquipos = mConexion.consultaEquipos();
            String[] datos;

            for (Object mListaEquipo : mListaEquipos) {
                datos = new String[2];
                mDatosEquipo = (DatosEquipo) mListaEquipo;
                datos[0] = "" + mDatosEquipo.getId();
                datos[1] = mDatosEquipo.getNombre();
                Tabla.addRow(datos);
            }
            this.tbl_Mod = new javax.swing.JTable();
            this.tbl_Mod.setModel(Tabla);
            this.tbl_Mod.getColumnModel().getColumn(0).setPreferredWidth(50);
            this.tbl_Mod.getColumnModel().getColumn(1).setPreferredWidth(250);
            if (this.tbl_Mod.getRowCount() > 0) {
                this.tbl_Mod.setRowSelectionInterval(0, 0);
            }
        } else {
            LBLmen1.setText("Error al consultar los equipos");
        }
        mConexion.desconectar();
    }

    private void BTN_altaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_altaActionPerformed
        DatosEquipo mDatosEquipo = new DatosEquipo();
        String text = TXT_Nom.getText();
        text = text.replaceAll(" ", "");
        if (text.length() != 0 && text.length() <= 35) {
            if (ValidarCajasNom()) {
                if (mConexion.conectar()) {
                    String NombreEq = mConexion.ConsultaNomEquipos(TXT_Nom.getText());
                    if (!NombreEq.equals(text)) {
                        mDatosEquipo.setNombre(TXT_Nom.getText());
                        mConexion.AltaEquipos(mDatosEquipo);
                        LBL_Men.setText("Equipo agregado exitosamente");
                    } else {
                        LBL_Men.setText("Ya existe un equipo con ese nombre");
                    }
                }
                mConexion.desconectar();
            } else {
                LBL_Men.setText("Escribe un nombre para un equipo");
            }
        } else {
            LBL_Men.setText("Nombre no válido");
        }
        mConexion.desconectar();
        ConsultaTablaAl();
        ConsultaTabla();
        consultaTablaMod();
        TXT_Nom.setText("");
    }//GEN-LAST:event_BTN_altaActionPerformed

    private void tblEQMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEQMouseClicked
        TXTnom.setText("");

        Selec = tblEQ.rowAtPoint(evt.getPoint());
        LBLid.setText(tblEQ.getModel().getValueAt(Selec, 0).toString());
        TXTnom.setText(tblEQ.getModel().getValueAt(Selec, 1).toString());
    }//GEN-LAST:event_tblEQMouseClicked

    private void BTNelimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNelimActionPerformed
        if (mConexion.conectar()) {
            if (ValidarCajasnom()) {
                mDatosEquipo.setId(Integer.parseInt(LBLid.getText()));
                if (mConexion.eliminarEquipo(mDatosEquipo)) {
                    LBLmen.setText("Equipo dado de baja exitosamente");
                } else {
                    LBLmen.setText("Este equipo tiene participantes, no se puede eliminar");
                }
            } else {
                LBLmen.setText("Selecciona el equipo que deseas eliminar");
            }
        } else {
            LBLmen.setText("Error al conectar");
        }
        mConexion.desconectar();
        ConsultaTabla();
        ConsultaTablaAl();
        consultaTablaMod();
        TXTnom.setText("");
    }//GEN-LAST:event_BTNelimActionPerformed

    public void ConsultaTablaAl() {
        Tabla = (DefaultTableModel) tblAl.getModel();
        int a = Tabla.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            Tabla.removeRow(Tabla.getRowCount() - 1);
        }

        if (mConexion.conectar()) {
            ArrayList mListaEquipos = mConexion.consultaEquipos();
            String[] datos;

            for (Object mListaEquipo : mListaEquipos) {
                datos = new String[2];
                mDatosEquipo = (DatosEquipo) mListaEquipo;
                datos[0] = "" + mDatosEquipo.getId();
                datos[1] = mDatosEquipo.getNombre();
                Tabla.addRow(datos);
            }
            this.tblAl = new javax.swing.JTable();
            this.tblAl.setModel(Tabla);
            this.tblAl.getColumnModel().getColumn(0).setPreferredWidth(50);
            this.tblAl.getColumnModel().getColumn(1).setPreferredWidth(250);
            if (this.tblAl.getRowCount() > 0) {
                this.tblAl.setRowSelectionInterval(0, 0);
            }
        } else {
            LBL_Men.setText("Error al consultar los equipos");
        }
        mConexion.desconectar();
    }

    private void TXTnomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTnomKeyTyped

    }//GEN-LAST:event_TXTnomKeyTyped

    private void BTNmodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNmodActionPerformed
        DatosEquipo vEquipo = new DatosEquipo();
        DatosEquipo nEquipo = new DatosEquipo();

        if (!TXTnom1.getText().equals("")) {
            String text = TXTnom1.getText();
            text = text.replaceAll(" ", "");
            if (text.length() != 0 && text.length() <= 35) {
                if (mConexion.conectar()) {
                    if (!"ID".equals(LBLid1.getText())) {
                        String NombreEq = mConexion.ConsultaNomEquipos(TXTnom1.getText());
                        if (!LBLid1.getText().equals("0")) {
                            if (!NombreEq.equals(text)) {
                                ID = Integer.parseInt(LBLid1.getText());
                                vEquipo.setId(ID);
                                nEquipo.setNombre(TXTnom1.getText());
                                if (mConexion.ModificarEquipo(vEquipo, nEquipo) && !LBLid1.getText().equals("0")) {
                                    LBLmen1.setText("Equipo modificado exitosamente");
                                    LBLid1.setText("0");
                                } else {
                                    LBLmen1.setText("Error al modificar");
                                    LBLid1.setText("0");
                                }
                            } else {
                                LBLmen1.setText("Ya existe un equipo con ese nombre");
                            }
                        } else {
                            LBLmen1.setText("Por favor selecciona un equipo de la tabla");
                        }
                    } else {
                        LBLmen1.setText("Por favor selecciona un equipo de la tabla");
                    }
                } else {
                    LBLmen1.setText("Error al conectar con la Base de Datos");
                }
                mConexion.desconectar();
            } else {
                LBLmen1.setText("Nombre no válido");
                LBLid1.setText("0");
            }
        } else {
            LBLmen1.setText("Por favor completa los campos");
        }
        ConsultaTabla();
        ConsultaTablaAl();
        consultaTablaMod();
        TXTnom1.setText("");
        LBLid1.setText("0");
    }//GEN-LAST:event_BTNmodActionPerformed

    private void tbl_ModMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ModMouseClicked
        TXTnom1.setText("");

        Selec = tbl_Mod.rowAtPoint(evt.getPoint());
        LBLid1.setText(tbl_Mod.getModel().getValueAt(Selec, 0).toString());
        TXTnom1.setText(tbl_Mod.getModel().getValueAt(Selec, 1).toString());
    }//GEN-LAST:event_tbl_ModMouseClicked

    private void TXTconKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTconKeyReleased
        Tabla = (DefaultTableModel) tbl_Con.getModel();
        int a = Tabla.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            Tabla.removeRow(Tabla.getRowCount() - 1);
        }

        if (mConexion.conectar()) {
            ArrayList mListaEquipos = mConexion.consultarEquiposFiltro(TXTcon.getText());
            String[] datos;

            for (Object mListaEquipo : mListaEquipos) {
                datos = new String[2];
                mDatosEquipo = (DatosEquipo) mListaEquipo;
                datos[0] = "" + mDatosEquipo.getId();
                datos[1] = mDatosEquipo.getNombre();
                Tabla.addRow(datos);
            }
            this.tbl_Con = new javax.swing.JTable();
            this.tbl_Con.setModel(Tabla);
            this.tbl_Con.getColumnModel().getColumn(0).setPreferredWidth(50);
            this.tbl_Con.getColumnModel().getColumn(1).setPreferredWidth(250);
            if (this.tbl_Con.getRowCount() > 0) {
                this.tbl_Con.setRowSelectionInterval(0, 0);
            }
        } else {
            LBLMen.setText("Error al consultar los equipos");
        }
        mConexion.desconectar();

    }//GEN-LAST:event_TXTconKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_alta;
    private javax.swing.JButton BTNelim;
    private javax.swing.JButton BTNmod;
    private javax.swing.JLabel LBLMen;
    private javax.swing.JLabel LBL_Men;
    private javax.swing.JLabel LBLid;
    private javax.swing.JLabel LBLid1;
    private javax.swing.JLabel LBLmen;
    private javax.swing.JLabel LBLmen1;
    private javax.swing.JTextField TXT_Nom;
    private javax.swing.JTextField TXTcon;
    private javax.swing.JTextField TXTnom;
    private javax.swing.JTextField TXTnom1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTable tblAl;
    private javax.swing.JTable tblEQ;
    private javax.swing.JTable tbl_Con;
    private javax.swing.JTable tbl_Mod;
    // End of variables declaration//GEN-END:variables
}
