/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import com.sun.glass.events.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eduardogarcia
 */
public final class Puntajes extends javax.swing.JInternalFrame {

    Conexion mConexion = new Conexion();
    int Complejidad = 0, IDConcursos = 0, IDEquipo = 0, IDConcursos1 = 0, IDConcursos2 = 0, IDEquipo1 = 0, ContadorColumna = 1, idPuntajes = 0 , IDEquipo2 = 0;
    /*Para modificar Datos*/ int idPuntajeViejo = 0, HorasNuevas = 0, HorasViejas = 0, MinutosNuevos = 0, MinutosViejos = 0;
                                
    DatosPuntajes mDatosPuntajes;
    DefaultTableModel Tabla = new DefaultTableModel();
    DefaultTableModel Tabla2 = new DefaultTableModel();

    /**
     * Creates new form Puntajes
     */
    public Puntajes() {
        initComponents();
        LlenarComboConcurso();
        LlenarComboEquipo();
        Tabla.addColumn("ID");
        Tabla.addColumn("Tiempo");
        Tabla.addColumn("Complejidad");
        Tabla2.addColumn("ID");
        Tabla2.addColumn("Tiempo");
        Tabla2.addColumn("Complejidad");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        CBHoras = new javax.swing.JComboBox<>();
        CBMinutos = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CBComplejidad = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        CBConcurso = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        CBEquipo = new javax.swing.JComboBox<>();
        LDBLPrueba = new javax.swing.JLabel();
        LBL_Mensajero = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        CBConcurso1 = new javax.swing.JComboBox<>();
        CBEquipo1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBPuntajes = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        CBConcurso2 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        CBEquipo2 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TBPuntajes1 = new javax.swing.JTable();
        LDBLPrueba1 = new javax.swing.JLabel();
        CBHoras1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        CBMinutos1 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        CBComplejidad1 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        CBConcurso3 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        CBEquipo3 = new javax.swing.JComboBox<>();
        LBL_Mensajero1 = new javax.swing.JLabel();
        LBL_Mensajero2 = new javax.swing.JLabel();

        setBorder(null);

        jPanel2.setBackground(new java.awt.Color(71, 120, 197));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("X");
        jLabel5.setToolTipText("Presione para salir");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jLabel5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel5KeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("APARTADO PUNTAJES");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(124, 124, 124)
                .addComponent(jLabel5)
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTabbedPane1KeyPressed(evt);
            }
        });

        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/16 (Save).jpg"))); // NOI18N
        jButton1.setText("Añadir puntaje");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        CBHoras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        CBMinutos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        CBMinutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBMinutosActionPerformed(evt);
            }
        });

        jLabel2.setText("Horas");

        jLabel3.setText("Minutos");

        jLabel4.setText("Complejidad:");

        CBComplejidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguna", "Básico", "Medio", "Avanzado" }));

        jLabel6.setText("Concurso:");

        CBConcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBConcursoActionPerformed(evt);
            }
        });

        jLabel7.setText("Equipo:");

        LDBLPrueba.setText("Tiempo:");

        LBL_Mensajero.setText("-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LDBLPrueba)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CBHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel3))
                                    .addComponent(CBMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(CBComplejidad, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CBConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(CBEquipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(LBL_Mensajero)))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LDBLPrueba))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CBComplejidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CBConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CBEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(173, 173, 173)
                .addComponent(LBL_Mensajero)
                .addGap(12, 12, 12))
        );

        jTabbedPane1.addTab("Alta", jPanel1);

        jTabbedPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTabbedPane2MousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane2MouseClicked(evt);
            }
        });
        jTabbedPane2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTabbedPane2KeyPressed(evt);
            }
        });

        jLabel9.setText("Concurso:");

        jLabel10.setText("Equipo:");

        CBConcurso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBConcurso1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/16 (Search).jpg"))); // NOI18N
        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        TBPuntajes.setModel(Tabla);
        TBPuntajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBPuntajesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBPuntajes);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/16 (Delete)_1.jpg"))); // NOI18N
        jButton3.setText("Borrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGap(133, 133, 133)
                            .addComponent(jButton2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGap(141, 141, 141)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel9))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CBConcurso1, 0, 177, Short.MAX_VALUE)
                                .addComponent(CBEquipo1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(CBConcurso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(CBEquipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Borrar", jPanel3);

        jTabbedPane1.addTab("Baja", jTabbedPane2);

        jLabel11.setText("Concurso:");

        CBConcurso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBConcurso2ActionPerformed(evt);
            }
        });

        jLabel12.setText("Equipo:");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/16 (Search).jpg"))); // NOI18N
        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/16 (User edit).jpg"))); // NOI18N
        jButton5.setText("Modificar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        TBPuntajes1.setModel(Tabla2);
        TBPuntajes1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBPuntajes1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TBPuntajes1);

        LDBLPrueba1.setText("Tiempo:");

        CBHoras1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabel8.setText("Horas");

        jLabel13.setText("Minutos");

        CBMinutos1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        CBMinutos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBMinutos1ActionPerformed(evt);
            }
        });

        jLabel14.setText("Complejidad:");

        CBComplejidad1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguna", "Básico", "Medio", "Avanzado" }));

        jLabel15.setText("Concurso:");

        CBConcurso3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBConcurso3ActionPerformed(evt);
            }
        });

        jLabel16.setText("Equipo:");

        LBL_Mensajero1.setText("-");

        LBL_Mensajero2.setText("-");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CBEquipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(CBConcurso2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(LDBLPrueba1)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CBHoras1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel8)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel13))
                                    .addComponent(CBMinutos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(CBComplejidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton5)
                            .addComponent(CBConcurso3, 0, 150, Short.MAX_VALUE)
                            .addComponent(CBEquipo3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LBL_Mensajero2, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(LBL_Mensajero1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(CBConcurso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CBEquipo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LDBLPrueba1)
                            .addComponent(CBHoras1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBMinutos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel13))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(CBComplejidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(CBConcurso3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(CBEquipo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(LBL_Mensajero2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LBL_Mensajero1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );

        jTabbedPane3.addTab("Cambiar", jPanel5);

        jTabbedPane1.addTab("Cambios", jTabbedPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5KeyPressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged

    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed

    }//GEN-LAST:event_jPanel2MousePressed

    private void CBMinutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBMinutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBMinutosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        GuardarPuntaje();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CBConcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBConcursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBConcursoActionPerformed

    private void CBConcurso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBConcurso1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBConcurso1ActionPerformed

    private void jTabbedPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane2MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jTabbedPane2MouseClicked

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1KeyPressed

    private void jTabbedPane2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane2MousePressed
        // TODO add your handling code here:       
    }//GEN-LAST:event_jTabbedPane2MousePressed

    private void jTabbedPane2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabbedPane2KeyPressed
        // TODO add your handling code here:        
    }//GEN-LAST:event_jTabbedPane2KeyPressed

    private void jTabbedPane1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabbedPane1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:        
        EliminarPuntaje();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            if (mConexion.conectar()) {
                mDatosPuntajes = new DatosPuntajes();
                mDatosPuntajes.setIdPuntajes(idPuntajes);
                if (mConexion.EliminarPuntajes(mDatosPuntajes)) {
                    LBL_Mensajero1.setText("Se ha eliminado el registro #" + idPuntajes);
                    LimpiarTabla();
                    EliminarPuntaje();
                }
            } else {
                LBL_Mensajero1.setText("No se ha podido conectar a la BD");
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void TBPuntajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBPuntajesMouseClicked
        // TODO add your handling code here:
        int Fila = TBPuntajes.rowAtPoint(evt.getPoint());
        String TemporalPuntaje = String.valueOf(TBPuntajes.getValueAt(Fila, 0));
        //LBL_Mensajero2.setText(String.valueOf(TBPuntajes.getValueAt(Fila,0)));
        idPuntajes = Integer.parseInt(TemporalPuntaje);
        //JOptionPane.showConfirmDialog(null, "Deseas borrar este puntaje", "Confirmar eliminacion", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
    }//GEN-LAST:event_TBPuntajesMouseClicked

    private void CBConcurso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBConcurso2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBConcurso2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        BuscarPuntajeParaModificar();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void TBPuntajes1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBPuntajes1MouseClicked
        // TODO add your handling code here:
        //Para llenado
        int Fila = TBPuntajes1.rowAtPoint(evt.getPoint());
        String TemporalPuntaje = String.valueOf(TBPuntajes1.getValueAt(Fila, 0));
        String TemporalHoras = String.valueOf(TBPuntajes1.getValueAt(Fila, 1)).substring(0, 2);
        String TemporalMinutos = String.valueOf(TBPuntajes1.getValueAt(Fila, 1)).substring(3, 5);
        String Complejidad =  String.valueOf(TBPuntajes1.getValueAt(Fila, 2));
        //LBL_Mensajero2.setText(String.valueOf(TBPuntajes.getValueAt(Fila,0)));

        idPuntajeViejo = Integer.parseInt(TemporalPuntaje);
        HorasViejas = Integer.parseInt(TemporalHoras);
        MinutosViejos = Integer.parseInt(TemporalMinutos);

        for (int i = 0; i < CBHoras1.getItemCount(); i++) {
            if (HorasViejas == Integer.parseInt(CBHoras1.getItemAt(i))) {
                CBHoras1.setSelectedIndex(i); //LLENAMOS HORAS
            }
        }
        for (int i = 0; i < CBMinutos1.getItemCount(); i++) {
            if (MinutosViejos == Integer.parseInt(CBMinutos1.getItemAt(i))) {
                CBMinutos1.setSelectedIndex(i); //LLENAMOS MINUTOS
            }
        }
        for (int i = 0; i < CBComplejidad1.getItemCount(); i++) {
            if (Complejidad.equals(CBComplejidad1.getItemAt(i))) {
                CBComplejidad1.setSelectedIndex(i); //LLENAMOS COMPLEJIDAD
            }
        }
        for (int i = 0; i < CBConcurso3.getItemCount(); i++) {
            if (CBConcurso2.getSelectedItem().equals(CBConcurso3.getItemAt(i))) {
                CBConcurso3.setSelectedIndex(i); //LLENAMOS CONCURSO
            }
        }
        for (int i = 0; i < CBEquipo3.getItemCount(); i++) {
            if (CBEquipo2.getSelectedItem().equals(CBEquipo3.getItemAt(i))) {
                CBEquipo3.setSelectedIndex(i); //LLENAMOS EQUIPO
            }
        }

    }//GEN-LAST:event_TBPuntajes1MouseClicked

    private void CBMinutos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBMinutos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBMinutos1ActionPerformed

    private void CBConcurso3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBConcurso3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBConcurso3ActionPerformed

    public void LlenarComboConcurso() {
        CBConcurso.addItem("Ninguno");
        CBConcurso1.addItem("Ninguno");
        CBConcurso2.addItem("Ninguno");
        CBConcurso3.addItem("Ninguno");
        if (mConexion.conectar()) {
            ArrayList mArrayList = new ArrayList();
            mArrayList = mConexion.ConsultaNombresConcurso();
            //LDBLPrueba.setText(mArrayList.get(0).toString());
            if (mArrayList != null) {

                for (int i = 0; i < mArrayList.size(); i++) {
                    CBConcurso.addItem(mArrayList.get(i).toString());
                    CBConcurso1.addItem(mArrayList.get(i).toString()); //Para baja
                    CBConcurso2.addItem(mArrayList.get(i).toString()); //Para consultar el que se va a modificar
                    CBConcurso3.addItem(mArrayList.get(i).toString()); //Para el que se va a cambiar
                }

            } else {
                LBL_Mensajero.setText("No tiene Concursos Dados de Alta");
            }
            mConexion.desconectar();
        } else {
            LBL_Mensajero.setText("No conectado a la BD");
        }
    }

    public void LlenarComboEquipo() {
        CBEquipo.addItem("Ninguno");
        CBEquipo1.addItem("Ninguno");
        CBEquipo2.addItem("Ninguno");
        CBEquipo3.addItem("Ninguno");
        if (mConexion.conectar()) {
            ArrayList mArrayList = new ArrayList();
            mArrayList = mConexion.ConsultaNombresEquipos();
            //LDBLPrueba.setText(mArrayList.get(0).toString());
            if (mArrayList != null) {

                for (int i = 0; i < mArrayList.size(); i++) {
                    CBEquipo.addItem(mArrayList.get(i).toString());
                    CBEquipo1.addItem(mArrayList.get(i).toString()); //Para Baja
                    CBEquipo2.addItem(mArrayList.get(i).toString()); //Para consultar el que se va a Modificar
                    CBEquipo3.addItem(mArrayList.get(i).toString()); //Para el que se va a cambiar
                }

            } else {
                LBL_Mensajero.setText("No tiene Equipos Dados de Alta");
            }
            mConexion.desconectar();
        } else {
            LBL_Mensajero.setText("No conectado a la BD");
        }
    }

    public void GuardarPuntaje() {
        if (CBComplejidad.getSelectedItem() == "Ninguna") {

        } else {
            if (CBComplejidad.getSelectedItem() == "Básico") {
                Complejidad = 1; //Basico
            } else {
                if (CBComplejidad.getSelectedItem() == "Medio") {
                    Complejidad = 2; //Medio
                } else {
                    if (CBComplejidad.getSelectedItem() == "Avanzado") {
                        Complejidad = 3; //Avanzado
                    } else {
                        LBL_Mensajero.setText("Selecciona una opcion de Complejidad");
                    }
                }
            }
        }
        //String Horas = (String) CBHoras.getSelectedItem();
        mDatosPuntajes = new DatosPuntajes();
        mDatosPuntajes.setHoras(Integer.parseInt(CBHoras.getSelectedItem().toString()));
        mDatosPuntajes.setMinutos(Integer.parseInt(CBMinutos.getSelectedItem().toString()));
        if (mConexion.conectar()) {
            if ((CBComplejidad.getSelectedItem() != "Ninguna") && (CBEquipo.getSelectedItem() != "Ninguno")) {
                IDConcursos = mConexion.ConsultarIDConcursos(CBConcurso.getSelectedItem().toString());
                IDEquipo = mConexion.ConsultarIDEquipos(CBEquipo.getSelectedItem().toString());
            } else {
                LBL_Mensajero.setText("Selecciona una opcion de complejidad y/o equipo");
            }
            mConexion.desconectar();
        } else {
            LBL_Mensajero.setText("No conectado a la BD");
        }
        mDatosPuntajes.setComplejidad(Complejidad);
        mDatosPuntajes.setConcursos_idConcursos(IDConcursos);
        mDatosPuntajes.setEquipos_idEquipos(IDEquipo);

        if (mConexion.conectar()) {
            if ((CBComplejidad.getSelectedItem() != "Ninguna") && (CBEquipo.getSelectedItem() != "Ninguno") && ((CBHoras.getSelectedItem() != "0") || (CBMinutos.getSelectedItem() != "0")) && (CBConcurso.getSelectedItem() != "Ninguno")) {
                if (mConexion.AltaPuntaje(mDatosPuntajes)) {
                    LBL_Mensajero.setText("Se guardo el puntaje");
                    CBHoras.setSelectedIndex(0);
                    CBMinutos.setSelectedIndex(0);
                    CBComplejidad.setSelectedIndex(0);
                    CBEquipo.setSelectedIndex(0);
                    CBConcurso.setSelectedIndex(0);
                }
            } else {
                LBL_Mensajero.setText("Favor de llenar bien los campos");
            }
            mConexion.desconectar();
        } else {
            LBL_Mensajero.setText("No conectado a la BD");
        }
    }

    public void LimpiarTabla() {
        DefaultTableModel TablaLimpiar = (DefaultTableModel) TBPuntajes.getModel();
        int a = TBPuntajes.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            TablaLimpiar.removeRow(TablaLimpiar.getRowCount() - 1);
        }
    }
    
    public void LimpiarTabla1() {
        DefaultTableModel TablaLimpiar = (DefaultTableModel) TBPuntajes1.getModel();
        int a = TBPuntajes1.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            TablaLimpiar.removeRow(TablaLimpiar.getRowCount() - 1);
        }
    }

    public void BuscarPuntaje() {
        LimpiarTabla();
        if (mConexion.conectar()) {

            if ((CBConcurso1.getSelectedItem() != "Ninguna") && (CBEquipo1.getSelectedItem() != "Ninguno")) {
                IDConcursos1 = mConexion.ConsultarIDConcursos(CBConcurso1.getSelectedItem().toString());
                IDEquipo1 = mConexion.ConsultarIDEquipos(CBEquipo1.getSelectedItem().toString());
            } else {
                LBL_Mensajero1.setText("Selecciona una opcion de concurso y/o equipo");
            }

            ArrayList mArrayListEliminarPuntajes = new ArrayList();
            mArrayListEliminarPuntajes = mConexion.ConsultarIDPuntajes(IDConcursos1, IDEquipo1);

            String[] Datos = null;
            if (mArrayListEliminarPuntajes != null) {
                if (ContadorColumna == 1) {
                    
                    ContadorColumna = 2;
                }

                for (int i = 0; i < mArrayListEliminarPuntajes.size(); i++) {
                    Datos = new String[3];
                    Datos[0] = mArrayListEliminarPuntajes.get(i).toString().substring(9); //ID
                    Datos[1] = mArrayListEliminarPuntajes.get(i).toString().substring(0, 8); //Tiempo
                    switch (Integer.parseInt(mArrayListEliminarPuntajes.get(i).toString().substring(8, 9))) {
                        case 1:
                            Datos[2] = "Básico";
                            break;
                        case 2:
                            Datos[2] = "Medio";
                            break;
                        case 3:
                            Datos[2] = "Avanzado";
                            break;
                    }

                    Tabla.addRow(Datos);
                }

            } else {
                LBL_Mensajero1.setText("No hay puntajes");
            }
            this.TBPuntajes = new javax.swing.JTable();
            this.TBPuntajes.setModel(Tabla);
            this.TBPuntajes.getColumnModel().getColumn(0).setPreferredWidth(50);
            this.TBPuntajes.getColumnModel().getColumn(1).setPreferredWidth(50);
            this.TBPuntajes.getColumnModel().getColumn(2).setPreferredWidth(100);
            if (this.TBPuntajes.getRowCount() > 0) {
                this.TBPuntajes.setRowSelectionInterval(0, 0);
            }

        } else {
            LBL_Mensajero1.setText("Error al consultar");
        }

        mConexion.desconectar();
        ContadorColumna = 1;
    }
    
    public void BuscarPuntajeParaModificar() {
        LimpiarTabla1();
        if (mConexion.conectar()) {

            if ((CBConcurso2.getSelectedItem() != "Ninguna") && (CBEquipo2.getSelectedItem() != "Ninguno")) {
                IDConcursos2 = mConexion.ConsultarIDConcursos(CBConcurso2.getSelectedItem().toString());
                IDEquipo2 = mConexion.ConsultarIDEquipos(CBEquipo2.getSelectedItem().toString());
            } else {
                LBL_Mensajero2.setText("Selecciona opcion correcta");
            }

            ArrayList mArrayListEliminarPuntajes = new ArrayList();
            mArrayListEliminarPuntajes = mConexion.ConsultarIDPuntajes(IDConcursos2, IDEquipo2);

            String[] Datos = null;
            if (mArrayListEliminarPuntajes != null) {
                if (ContadorColumna == 1) {
                    
                    ContadorColumna = 2;
                }

                for (int i = 0; i < mArrayListEliminarPuntajes.size(); i++) {
                    Datos = new String[3];
                    Datos[0] = mArrayListEliminarPuntajes.get(i).toString().substring(9); //ID
                    Datos[1] = mArrayListEliminarPuntajes.get(i).toString().substring(0, 8); //Tiempo
                    switch (Integer.parseInt(mArrayListEliminarPuntajes.get(i).toString().substring(8, 9))) {
                        case 1:
                            Datos[2] = "Básico";
                            break;
                        case 2:
                            Datos[2] = "Medio";
                            break;
                        case 3:
                            Datos[2] = "Avanzado";
                            break;
                    }

                    Tabla2.addRow(Datos);
                }

            } else {
                LBL_Mensajero2.setText("No hay puntajes");
            }
            this.TBPuntajes1 = new javax.swing.JTable();
            this.TBPuntajes1.setModel(Tabla2);
            this.TBPuntajes1.getColumnModel().getColumn(0).setPreferredWidth(50);
            this.TBPuntajes1.getColumnModel().getColumn(1).setPreferredWidth(50);
            this.TBPuntajes1.getColumnModel().getColumn(2).setPreferredWidth(100);
            if (this.TBPuntajes1.getRowCount() > 0) {
                this.TBPuntajes1.setRowSelectionInterval(0, 0);
            }

        } else {
            LBL_Mensajero2.setText("Error al consultar");
        }

        mConexion.desconectar();
    }
    
    public void EliminarPuntaje() {
        try {
            if (mConexion.conectar()) {
                mDatosPuntajes = new DatosPuntajes();
                mDatosPuntajes.setIdPuntajes(idPuntajes);
                if (mConexion.EliminarPuntajes(mDatosPuntajes)) {
                    LBL_Mensajero1.setText("Se ha eliminado el registro #" + idPuntajes);
                    LimpiarTabla();
                    BuscarPuntaje();
                }
            } else {
                LBL_Mensajero1.setText("No se ha podido conectar a la BD");
            }
        } catch (Exception e) {

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBComplejidad;
    private javax.swing.JComboBox<String> CBComplejidad1;
    private javax.swing.JComboBox<String> CBConcurso;
    private javax.swing.JComboBox<String> CBConcurso1;
    private javax.swing.JComboBox<String> CBConcurso2;
    private javax.swing.JComboBox<String> CBConcurso3;
    private javax.swing.JComboBox<String> CBEquipo;
    private javax.swing.JComboBox<String> CBEquipo1;
    private javax.swing.JComboBox<String> CBEquipo2;
    private javax.swing.JComboBox<String> CBEquipo3;
    private javax.swing.JComboBox<String> CBHoras;
    private javax.swing.JComboBox<String> CBHoras1;
    private javax.swing.JComboBox<String> CBMinutos;
    private javax.swing.JComboBox<String> CBMinutos1;
    private javax.swing.JLabel LBL_Mensajero;
    private javax.swing.JLabel LBL_Mensajero1;
    private javax.swing.JLabel LBL_Mensajero2;
    private javax.swing.JLabel LDBLPrueba;
    private javax.swing.JLabel LDBLPrueba1;
    private javax.swing.JTable TBPuntajes;
    private javax.swing.JTable TBPuntajes1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    // End of variables declaration//GEN-END:variables
}
